<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>inai-inai</AssemblyName>

    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <PublishDir>..</PublishDir>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>

    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Version>0.4.0</Version>
    <Authors>taidalog</Authors>
    <Description>A privacy tool that blurs faces in images.</Description>
    <Copyright>Copyright 2026 taidalog</Copyright>
    <RepositoryUrl>https://github.com/taidalog/inai-inai</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Utility.fs" />
    <Compile Include="Resources.fs" />
    <Compile Include="Path.fs" />
    <Compile Include="Arguments.fs" />
    <Compile Include="Image.fs" />
    <Compile Include="Process.fs" />
    <Compile Include="InaiInai.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Argu" Version="6.2.5" />
    <PackageReference Include="FaceONNX" Version="4.1.1.3" />
    <PackageReference Include="OpenCvSharp5.GdipExtensions" Version="5.0.0.20260730" />
    <PackageReference Include="OpenCvSharp5.Windows" Version="5.0.0.20260723" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

</Project>
